# Generated by Django 6.0.5 on 2026-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('medico', models.CharField(max_length=50)),
                ('especialidade', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['data', 'hora'],
            },
        ),
    ]
