# Generated by Django 6.0.5 on 2026-05-17 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especialidade', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
                'db_table': 'especialistas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data', 'hora'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.AlterModelTable(
            name='consulta',
            table='consultas',
        ),
        migrations.AddField(
            model_name='consulta',
            name='especialista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='consultas.especialista'),
            preserve_default=False,
        ),
    ]
