# Generated by Django 6.0.5 on 2026-05-18 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_especialista_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data', 'horario_selecionado'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='hora',
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='consultas.especialista')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='horario_selecionado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_agendadas', to='consultas.horariodisponivel'),
            preserve_default=False,
        ),
    ]
